repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
    -   id: autoflake
        name: autoflake
        exclude: ^templates/
        args: ["-r", "-i", "--remove-all-unused-imports", "--remove-unused-variables"]

-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        name: isort (python)
        exclude: ^templates/

    -   id: isort
        name: isort (cython)
        types: [cython]
        exclude: ^templates/

    -   id: isort
        name: isort (pyi)
        types: [pyi]
        exclude: ^templates/

-   repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
    -   id: black
        exclude: ^templates/
        args: ["-v"]
