"""empty message

Revision ID: 94a5b5198867
Revises:
Create Date: 2022-03-12 00:15:21.130502

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "94a5b5198867"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("counter", sa.Column("value", sa.Integer(), nullable=False))
    op.drop_column("counter", "name")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "counter",
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    )
    op.drop_column("counter", "value")
    # ### end Alembic commands ###
